services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketsDB
  #  for visual representation of the database
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"