services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketingdb
  #  for visual representation of the database
  adminer:
    image: adminer:latest
    ports:
      - "8888:8080"
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    # made it run on port 9090 to avoid conflict with ticket-service LOCALLY
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    # persist users through container restarts
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file # save configuration to disk

volumes:
  keycloak-data:
    driver: local