spring:
  application:
    name: ticket-service

  # Database Connection
  datasource:
    url: jdbc:postgresql://localhost:5433/ticketingdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    #  JPA
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # Keycloak Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/event-ticket-platform

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000