spring:
  application:
    name: ticket-service

  # Database Connection
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketsDB
    username: user
    password: password
    #  JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # Keycloak Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/event-ticket-platform